[package]
name = "thumbnailgen"
version = "0.1.0"
authors = ["Janne Mareike Koschinski <janne@kuschku.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-dev = "0.3.8"
log = "0.4.8"
image = "0.23.0"
enum_primitive = "0.1.1"
failure = "0.1.6"
fraction = "0.6.2"
mime = "0.3.16"
time = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"